export const productArray = [
  {
    name: "AC: Valhalla",
    image: "images/indeximg/acvalhallaartcomp.jpg",
    category: "Action adventure",
    id: "1",
    price: 65.99,
    tag: "Trending",
    video: "https://www.youtube.com/embed/ssrNcwxALS4",
    description:
      "Play as a fierce Viking warrior, Eivor, as you traverse across the icy North Sea to the breath-taking landscapes of England's broken kingdoms. Raid your enemies, establish your new settlement, and build your political power to earn a place amongst the gods in Assassin's Creed Valhalla.",
  },
  {
    name: "The Last of Us II",
    image: "images/indeximg/tla2artcomp.jpg",
    category: "Action-adventure",
    id: "2",
    price: 49.99,
    tag: "Trending",
    video: "https://www.youtube.com/embed/qPNiIeKMHyg",
    description:
      "The Last of Us Part II is the perfect combination of an excellent Hollywood movie with a fat budget with fun and flowing gameplay. The phenomenal writing will touch every player and won't leave an eye dry of tears. Combat and exploration are challenging and lead the player to use creativity and improvisation. A real masterpiece and a must-have for every PS4 owner.",
  },
  {
    name: "Ghost OT",
    image: "images/indeximg/ghostsoftsushimacomp.jpg",
    category: "Action-adventure",
    id: "3",
    price: 59.99,
    tag: "Trending",
    video: "https://www.youtube.com/embed/iqysmS4lxwQ",
    description:
      "The year is 1274 CE on the island of Tsushima. Samurai warriors are the legendary defenders of Japan until the fearsome Mongol Empire invades, wreaking havoc and conquering Tsushima, defeating nearly all samurai stationed on Tsushima Island. As one of the last surviving samurai, Jin Sakai rises from the ashes to fight back with help from his allies, but the honorable tactics and code of the samurai won't lead to a possible victory over the Mongols. Jin must move beyond samurai traditions to forge a new way of fighting – the way of the Ghost – as he wages an unconventional war for the freedom of Japan.",
  },
  {
    name: "Fall Guys",
    image: "images/indeximg/fallcomp.jpg",
    category: "Action-adventure",
    id: "4",
    price: 9.51,
    tag: "Trending",
    video: "https://www.youtube.com/embed/Wj3dUvGLjNQ",
    description:
      "Fall Guys: Ultimate Knockout flings hordes of contestants together online in a mad dash through round after round of escalating chaos until one victor remains. Battle bizarre obstacles, shove through unruly competitors, and overcome the unbending laws of physics as you stumble towards greatness.",
  },
  {
    name: "Guitar Hero 3",
    image: "images/indeximg/gh3comp.jpg",
    category: "Action-adventure",
    id: "5",
    price: 69.99,
    tag: "Trending",
    video: "https://www.youtube.com/embed/aCtwnGyEGOU",
    description:
      "The third game from the Guitar Hero series is going to rock your face off. You will channel your inner guitar god as you thrash your way through all sorts of venues. ... The expanded online multiplayer game modes will also allow axe-shredders worldwide to compete head-to-head for true legendary rock status.",
  },
  {
    name: "Super Mario 64",
    image: "images/indeximg/sm64artcomp.jpg",
    category: "Action-adventure platformer",
    id: "6",
    price: 13.65,
    tag: "Trending",
    video: "https://www.youtube.com/embed/8Fk5sRwbEWI",
    description:
      "Super Mario 64 is a 1996 platform game for the Nintendo 64 and the first Super Mario game to feature 3D gameplay. It was developed by Nintendo EAD and published by Nintendo. As Mario, the player collects power stars while exploring Princess Peach's castle and must rescue her from Bowser.",
  },
  {
    name: "Call of Duty Black Ops Cold War",
    image: "images/indeximg/coldwarsmall.jpg",
    category: "Action adventure",
    id: "7",
    price: 89.99,
    tag: "pre-order",
    video: "https://www.youtube.com/embed/aTS9n_m7TW0",
    description:
      "Call of Duty: Black Ops Cold War is a 2020 first-person shooter video game developed by Treyarch and Raven Software and published by Activision. It features a seasonal content system similar to Call of Duty: Modern Warfare (2019), which includes a battle pass as well as free maps and weapons added every season.",
  },
  {
    name: "Cyberpunk 2077",
    image: "images/indeximg/cyberpunkcol1.jpg",
    category: "Action-adventure",
    id: "8",
    price: 69.99,
    tag: "pre-order",
    video: "https://www.youtube.com/embed/DvVjkqB3LH0",
    description:
      "Cyberpunk 2077 is an open world, action-adventure story set in Night City, a megalopolis obsessed with power, glamour and body modifications. You play as V, a mercenary outlaw going after a one-of-a-kind implant that is the key to immortality. You can customize your character’s cyberware, skillset and playstyle, and explore a vast city where the choices you make shape the story and the world around you.",
  },
  {
    name: "2k21 Mamba Forever Edition",
    image: "images/indeximg/2k21coversmall.jpg",
    category: "Action-adventure",
    id: "9",
    price: 99.99,
    tag: "pre-order",
    video: "https://www.youtube.com/embed/KpLO9sIauRA",
    description:
      "NBA 2K21 is a basketball simulation video game that was developed by Visual Concepts and published by 2K Sports, based on the National Basketball Association (NBA). It is the 22nd installment in the NBA 2K franchise and the successor to NBA 2K20.",
  },
  {
    name: "Gears Tactics",
    image: "images/indeximg/gearssmall.jpg",
    category: "Action-adventure",
    id: "10",
    price: 59.99,
    tag: "pre-order",
    video: "https://www.youtube.com/embed/M5eYR5Pu4Io",
    description:
      "Gears Tactics is the fast-paced, turn-based strategy game from one of the most-acclaimed video game franchises – Gears of War. Outnumbered and fighting for survival, recruit and command your squad to hunt down an evil mastermind who makes monsters.",
  },
  {
    name: "Horizon Zero Dawn",
    image: "images/indeximg/Horizoncol2.jpg",
    category: "Action adventure",
    id: "11",
    price: 30.71,
    oldPrice: 59.12,
    decrease: "-63%",
    tag: "near-new",
    video: "https://www.youtube.com/embed/u4-FCsiF5x4",
    description:
      "Horizon Zero Dawn is a 2017 action role-playing game developed by Guerrilla Games and published by Sony Interactive Entertainment. The plot follows Aloy, a young hunter in a world overrun by machines, who sets out to uncover her past. The player can explore the open world to discover locations and take on side quests.",
  },
  {
    name: "Call of Duty Black Ops III",
    image: "images/indeximg/CodBO3small.jpg",
    category: "Action-adventure",
    id: "12",
    price: 26.21,
    oldPrice: 70.94,
    decrease: "-63%",
    tag: "near-new",
    video: "https://www.youtube.com/embed/qAUYNIDEJ6o",
    description:
      "Call of Duty®: Black Ops 3 is a dark, gritty future where a new breed of Black Ops soldier emerges and the lines are blurred between our own humanity and the cutting-edge military technology that define the future of combat",
  },
  {
    name: "Dead by Daylight",
    image: "images/indeximg/deadbydaylightsmall.jpg",
    category: "Action-adventure",
    id: "13",
    price: 7.38,
    oldPrice: 23.64,
    decrease: "-68%",
    tag: "near-new",
    video: "https://www.youtube.com/embed/JGhIXLO3ul8",
    description:
      "Dead by Daylight is an asymmetrical multiplayer (4vs1) horror game where one player takes on the role of the savage Killer, and the other four players play as Survivors, trying to escape the Killer and avoid being caught and killed.",
  },
  {
    name: "Overwatch",
    image: "images/indeximg/OVERWATCHsmall.jpg",
    category: "Action-adventure",
    id: "14",
    price: 18.06,
    oldPrice: 59.12,
    decrease: "-63%",
    tag: "near-new",
    video: "https://www.youtube.com/embed/dushZybUYnM",
    description:
      "Overwatch is a colorful team-based shooter game starring a diverse cast of powerful heroes. Travel the world, build a team, and contest objectives in exhilarating 6v6 combat.",
  },
  {
    name: "Minecraft: Windows 10 Edition (PC)",
    image: "images/indeximg/minecraftsmall.jpg",
    category: "Action adventure",
    id: "15",
    price: 89.99,
    tag: "best",
    video: "https://www.youtube.com/embed/MmB9b5njVbA",
    description:
      "Minecraft is a video game in which players create and break apart various kinds of blocks in three-dimensional worlds. The game's two main modes are Survival and Creative. In Survival, players must find their own building supplies and food. They also interact with blocklike mobs, or moving creatures.",
  },
  {
    name: "Call of Duty Modern Warfare 2",
    image: "images/indeximg/mw2coversmall.jpg",
    category: "Action-adventure",
    id: "16",
    price: 13.37,
    tag: "best",
    video: "https://www.youtube.com/embed/blshENwbHgs",
    description:
      "Call of Duty: Modern Warfare 2 is a 2009 first-person shooter game developed by Infinity Ward and published by Activision. An expansive multiplayer mode is featured in the game, with several new features and modes that were not seen in its predecessor.",
  },
  {
    name: "Grand Theft Auto V",
    image: "images/indeximg/CoverArt-GTAVsmall.jpg",
    category: "Action-adventure",
    id: "17",
    price: 27.62,
    tag: "best",
    video: "https://www.youtube.com/embed/QkkoHAzjnUs",
    description:
      "Grand Theft Auto V is an action-adventure game played from either a third-person or first-person perspective. Players complete missions—linear scenarios with set objectives—to progress through the story. Outside of the missions, players may freely roam the open world.",
  },
  {
    name: "The Elder Scrolls V",
    image: "images/indeximg/SKYRIMcoversmall.jpg",
    category: "Action-adventure",
    id: "18",
    price: 33.57,
    tag: "best",
    video: "https://www.youtube.com/embed/JSRtYpNRoN0",
    description:
      "The Elder Scrolls V: Skyrim is an action role-playing game, playable from either a first or third-person perspective. The player may freely roam over the land of Skyrim—an open world environment consisting of wilderness expanses, dungeons, caves, cities, towns, fortresses, and villages.",
  },
];
